service: aws-python-sample

provider:
  name: aws
  runtime: python3.9
  environment:
    AWS_ENV: Dev
    AWS_DEFAULT_REGION: ap-southeast-1

plugins:
  - serverless-offline

functions:
  playground:
    handler: lambda_function.lambda_handler
    events: 
      - http:
          method: ANY
          path: /dummy
      
